### REQUIRED

namespace: thomasbuchinger
name: common
version: 0.0.1
readme: README.md
authors:
- Thomas Buchinger <thomas.buchinger@outlook.com>


### OPTIONAL but strongly recommended
description: Common Roles used in multiple projects
repository: http://github.com/thomasbuchinger/???
license_file: 'LICENSE'
tags: []
# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies:
  ansible.posix: ">0.0.0"
  community.general: ">0.0.0"
  community.libvirt: ">0.0.0"
  community.crypto: ">0.0.0"
  oasis_roles.system: ">0.0.0"

