---
galaxy_info:
  author: Thomas Buchinger
  description: Add OKD Console to the kubernetes cluster

  license: Apache-2.0
  min_ansible_version: 2.6
  platforms:
    - name: CentOS
      versions:
      - 7
      - 8
  galaxy_tags: []
dependencies:
  - base_kubernetes

