galaxy_info:
  author: Thomas Buchinger
  description: Shell DDNS Client with Cloudflare support

  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: CentOS
      versions:
      - 7
      - 8
  galaxy_tags: []
dependencies: []

