---
- name: Check / Variables are set
  ansible.builtin.fail:
    msg: "Required variable not found: server={{ mount.server }} remote_path={{ mount.remote_path }} mountpoint={{ mount.path }}"
  when: (nfs_server | default('') | length < 1) or
    (nfs_share_name | default('') | length < 1) or
    (nfs_path | default('') | length < 1)

- name: Check / Path does not start with /
  ansible.builtin.fail:
    msg: Remote Path cannot start with '/' (slash)
  when: nfs_share_name[0] == '/'

