---
- import_tasks: check.yaml
  tags:
    - config_nfs_client
- name: "Install / Install NFS Utils"
  ansible.builtin.yum:
    name: nfs-utils
    state: present
  become: yes
  tags:
    - config_nfs_client

- include_tasks: mount.yaml
  loop: "{{ nfs_mounts | default([]) }}"
  loop_control:
    loop_var: mount
  tags:
    - config_nfs_client
    - config_nfs_client:mount
