---
- name: "Mount / creating mount point for share {{ nfs_path }}"
  ansible.builtin.file:
    path: "{{ nfs_path }}"
    state: directory
  become: yes

- name: "Mount / Mount NFS share {{ nfs_path }} from {{ nfs_server }}:/{{ nfs_share_name }}"
  ansible.posix.mount:
    name: "{{ nfs_path }}"
    src: "{{ nfs_server }}:/{{ nfs_share_name }}"
    fstype: nfs
    opts: "{{ nfs_mount_opts | default(omit) }}"
    state: mounted
  become: yes
