- name: sshd / Set global options
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regex | default(omit) }}"
    state: present
    path: /etc/ssh/sshd_config
    backup: yes
    firstmatch: yes
  notify: restart_ssh
  loop:
    - { line: "AddressFamily inet", regex: "AddressFamily" }
    - { line: "Protocol 2", regex: "Protocol" }
    - { line: "X11Forwarding {{ sshd_x11_forwarding | ternary('yes', 'no') }}", regex: "^X11Forwarding" }
    - { line: "PermitUserEnvironment no", regex: "PermitUserEnvironment" }
    - { line: "AllowAgentForwarding no", regex: "AllowAgentForwarding" }
    - { line: "AllowTcpForwarding no", regex: "AllowTcpForwarding" }
    - { line: "PermitTunnel no", regex: "PermitTunnel" }

    - { line: "AllowGroups root admins {{ sshd_allow_groups }}", regex: "AllowGroups" }

    - { line: "PermitRootLogin {{ sshd_permit_root_login | ternary('yes', 'no') }}", regex: "^PermitRootLogin" }
    - { line: "PasswordAuthentication {{ sshd_password_authentication | ternary('yes', 'no') }}", regex: "^PasswordAuthentication" }
    - { line: "PermitEmptyPasswords no", regex: "^#?PermitEmptyPasswords" }
    - { line: "ChallengeResponseAuthentication no", regex: "^ChallengeResponseAuthentication" }
    - { line: "KerberosAuthentication no", regex: "KerberosAuthentication" }
    - { line: "GSSAPIAuthentication no", regex: "^GSSAPIAuthentication" }
  
- name: sshd / Configure external access
  blockinfile:
    content: "{{ item.content }}"
    path: /etc/ssh/sshd_config
  notify: restart_ssh
  when: sshd_disallow_root_from_host is defined
  loop:
  - { content: "Match Host {{ sshd_disallow_root_from_host }}\n  PermitRootLogin no" }
