---
- name: Repo / Terraform
  ansible.builtin.yum_repository:
    name: terraform
    description: Hashicorp Terraform Repo
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: yes
  become: yes
- name: Repo / Plugin / libvirt-provider
  ansible.builtin.yum_repository:
    name: terraform-libvirt-provider
    description: Libvirt Provider for terraform
    baseurl: https://download.opensuse.org/repositories/systemsmanagement:/terraform/Fedora_32/
    gpgkey: https://download.opensuse.org/repositories/systemsmanagement:/terraform/Fedora_32/repodata/repomd.xml.key
    gpgcheck: yes
  become: yes
  tags:
    - comp_terraform:plugin
- name: Terraform / Install binary
  ansible.builtin.yum:
    name: 
      - terraform
      - terraform-provider-libvirt
    state: present
  become: yes
  tags:
    - comp_terraform:plugin

- name: Terraform / Create project directorys
  ansible.builtin.file:
    path: "{{ tf_root }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
    state: directory
  loop:
    - .terraform.d/plugins
  become: yes

