---
- name: Check / Download URL
  ansible.builtin.fail:
    msg: "Unable to build download URL: base_url={{ ddns_client_download_url_base }} branch={{ ddns_client_branch }} "
  when: (ddns_client_download_base_url | default('') | length < 1) or
    (ddns_client_branch | default('') | length < 1) or
    (ddns_client_executeable | default('') | length < 1)

- name: Check / Mandatory DDNS parameters
  ansible.builtin.fail:
    msg: "Mandatory Parameter not found: Domain: {{ ddns_client_domain }} Hostnames: {{ ddns_client_hostnames }} Provider: {{ ddns_client_provider }}"
  when: (ddns_client_domain | default('') | length < 1) or
    (ddns_client_hostnames | default('') | length < 1) or
    (ddns_client_provider | default('') | length < 1)

- name: Check / Token Auth
  ansible.builtin.fail:
    msg: "Authtype Token: No token found!"
  when: not (
      (ddns_client_authtype == "token") and
      (ddns_client_token | default('') | length > 0)
    )

- name: Check / systemd service
  ansible.builtin.fail:
    msg: "Not a systemd distribution"
  when: not "/usr/bin/systemctl" is file
