---
apiVersion: v1
kind: Namespace
metadata:
  name: nas

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-ingress
  namespace: nas
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
  #  traefik.ingress.kubernetes.io/router.middlewares: nas-strip@kubernetescrd
spec:
  rules:
  - host: nas.{{ ansible_default_ipv4.address }}.nip.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: freenas-web
            port:
              number: 80
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: freenas-web
            port:
              number: 80
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: freenas-web
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-ingress-console
  namespace: nas
spec:
  rules:
  - host: nas.{{ ansible_default_ipv4.address }}.nip.io
    http:
      paths:
      - path: /console
        pathType: Prefix
        backend:
          service:
            name: console
            port:
              number: 80
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#    name: strip
#    namespace: nas
#spec:
#  stripPrefix:
#    prefixes:
#      - /console
#      - /access
#      - /files
#    forceSlash: false

---
apiVersion: v1
kind: Service
metadata:
  name: freenas-web
  namespace: nas
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  type: ExternalName
  externalName: {{ freenas_server }}
  ports:
  - name: http
    port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: nas
spec:
  type: ExternalName
  externalName: console.{{ ansible_default_ipv4.address }}.nip.io

