---
apiVersion: v1
kind: Namespace
metadata:
  name: nas

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-ingress
  namespace: nas
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: freenas-web
            port:
              number: 80
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: freenas-web
            port:
              number: 80
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: freenas-web
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: freenas-web
  namespace: nas
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  type: ExternalName
  externalName: {{ freenas_url }}
  ports:
  - name: http
    port: 80

