---
- name: "Namespace Apply / {{ k8s_app }} / Check mandatory variables"
  ansible.builtin.fail:
    msg: "k8s_namespace, k8s_app or k8s_work_dir  not set!"
  when: (k8s_namespace | default('') | length < 1 ) or
   (k8s_app | default('') | length < 1 ) or
   (k8s_work_dir | default('') | length < 1 )
- name: "Namespace Apply / {{ k8s_app }} / Ensure workdir exists"
  ansible.builtin.file:
    path: "{{ k8s_work_dir }}"
    state: directory

- name: "Namspace Apply / {{ k8s_app }} / Ensure Namespace exists: {{ k8s_namespace }}"
  command:
    stdin: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ k8s_namespace }}
    argv: [ "kubectl", "apply", "-f", "-"]
  register: create_ns
  changed_when: '"unchanged" in create_ns.stdout_lines'
  become: yes

- name: "Namespace Apply / {{ k8s_app }} / Copy Manifests"
  copy:
    content: "{{ k8s_manifest }}"
    dest: "{{ k8s_work_dir }}/{{ k8s_app }}.yaml"
- name: "Namspace Apply / {{ k8s_app }} / Apply"
  command: 
    argv: ["kubectl", "apply", "-n", "{{ k8s_namespace }}", "-f", "{{ k8s_work_dir }}/{{ k8s_app }}.yaml"]
  register: apply_manifest
  changed_when: (apply_manifest.stdout_lines | map('regex_search', ' unchanged$') | select('string') | list | length) != (apply_manifest.stdout_lines | length)
  become: yes
