galaxy_info:
  author: Thomas Buchinger
  description: Setup a ansible user with ssh key authentication and sudo
  license: Apache-2.0
  min_ansible_version: 2.4
  platforms:
    - name: CentOS
      versions:
        - 7
        - 8
  galaxy_tags: []

dependencies: []

