---
apiVersion: v1
kind: Namespace
metadata:
  name: syncthing

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: syncthing
spec:
  selector:
    matchLabels:
      k8s-app: syncthing
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: syncthing
    spec:
      containers:
        - name: syncthing
          image: syncthing/syncthing
          ports:
            - containerPort: 8384
            - containerPort: 22000
              hostPort: 22000
          volumeMounts:
            {% for share in syncthing_folders %}
            - name: share-{{ share.name }}
              mountPath: /var/syncthing/{{ share.name }}
              readonly: {{ share.readonly | default('false') }}
            {% endfor %}
    volumes:
      - name: config
        hostPath:
          path: /share/nas/internal/syncthing
      {% for share in synthing_folders %}
      - name: share-{{ share.name }}
        hostPath:
          path: {{ share.path }}
      {% endfor %}

---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: syncthing
spec:
  selector:
    k8s-app: syncthing
  ports:
    - name: http
      port: 8384
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing
  namespace: syncthing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: nas.{{ ansible_default_ipv4.address }}.nip.io
      http:
        paths:
          - path: /(sync/?)($)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(rest.*)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(syncthing.*)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(assets.*)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(vendor.*)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(qr.*)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(theme-assets.*)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(meta.js)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(modal.html)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
          - path: /(sync)?(themes.json)
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-host
  namespace: syncthing
spec:
  rules:
    - host: sync.{{ ansible_default_ipv4.address }}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
