---
foreman_version: latest

foreman_skip_compute_kvm: false
foreman_skip_compute_vmware: false

foreman_hostname: "{{ ansible_hostname }}"
foreman_domain: ""
foreman_work_dir: ""
foreman_admin_password: ""
foreman_admin_email: "{{ ansible_user }}@{{ ansible_fqdn }}"
foreman_key_name: id_rsa

foreman_python: python38:3.8
foreman_ruby: ruby:2.7

#foreman_default_net_ns: "{{ dns_ip }}"
#foreman_default_net_forwarders: "{{ dns_server }}"
#foreman_default_net_dns_revzone: 0.0.10.in-addr.arpa

foreman_groups: []
  #- { name: "example", arch:  "x86_64", domain: "{{ foreman_domain }}", env: "production", os: "", medium: "", compute_profile: "", compute_resource: "", pxe:"", ptable: "", root_password: "", subnet: "" }

foreman_environments:
  - production

foreman_flavors: []
  #- { name: "example", cpus: 1, memory: 1, size: 50, network: "", storage_location: "", storage_thin: true}
    
foreman_networks: []
  #- { name: "example", default: false, networkid: "192.168.1.0", netmask: "255.255.255.0", gateway: "192.168.1.1", dns1: "1.1.1.1", dns2: "8.8.8.8", hoststart: "192.168.1.10", hostend: "192.168.1.49" }
 
foreman_compute: []
  #- { name: "kvm-example", type: "kvm", url: "", default: false }
  #- { name: "vmware-example", type: "vmware", default: false, server: "<server>", user: "<user>", password: "<password>"}

