---
- name: "User / Create User {{ enroll_username }}"
  ansible.builtin.user:
    name: "{{ enroll_username }}"
    password: '!'
    state: present
    comment: "Ansible Automation user"
    create_home: yes
    home: "{{ enroll_home }}"
    system: yes
- name: User / Authorize public key
  ansible.posix.authorized_key:
    user: "{{ enroll_username }}"
    key: "{{ enroll_public_key }}"
    state: present

- name: sudo / Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present
- name: sudo / Configure sudoers for ansible
  ansible.builtin.copy:
    content: >
      {{ enroll_username }} ALL=(ALL) NOPASSWD: ALL
    dest: "/etc/sudoers.d/{{ enroll_username }}"
