---
- name: Check / Mandatory variables
  ansible.builtin.assert:
    that:
      - key_exchange_user is defined
      - key_exchange_user | length > 1
    fail_msg: "Missing mandatory parameter: key_exchange_user={{ key_exchange_user }}"

- name: Discover / Available users
  ansible.builtin.command:
    cmd: "cut -d : -f 1 /etc/passwd"
  register: available_users
  changed_when: false
- name: Check / key_exchange_user exists
  ansible.builtin.assert:
    that:
      - key_exchange_user in available_users.stdout
    fail_msg: "{{ key_exchange_user }} does not exist"

- name: Check / authorized_keys task requires generate_keys task
  ansible.builtin.assert:
    that:
      - not( key_exchange_authorized_keys == true and key_exchange_generate_keys == false )
    fail_msg: "Cannot perform 'authorize keys' without generating keys first! (You can manually generate keys first though)"

- name: "Summary:"
  ansible.builtin.debug:
    msg: "Exchange SSH keys for user {{ key_exchange_user }} between {{ play_hosts | join(', ') }}"
