- name: Create ansible user
  hosts: all
  vars:
    ansible_user: root
  roles:
    - role: config_enroll_ansible
      vars:
        enroll_user: ansible
        enroll_public_key: "{{ ansible_public_key }}"
        enroll_home: "{{ work_dir }}"
