- name: Create ansible user
  hosts: all
  vars:
    ansible_user: root
  roles:
    - role: config_enroll_ansible
      vars:
        enroll_user: ansible
        enroll_public_key: "{{ var_enroll_public_key }}"
        enroll_home: "{{ var_enroll_home }}"
