- import_playbook: common_enroll-in-ansible.yaml
- name: Install NAS Server
  hosts: berni,labnas
  vars:
    k8s_work_dir: "{{ work_dir }}/k8s }}"
  pre_tasks:
    - name: k3s / Fix-1 / Re-enable Firewalld for ansible run
      systemd:
        name: firewalld
        state: started
  roles:
    - oasis_roles.system.chrony
    - app_cockpit
    - role: comp_sshd
      vars:
        sshd_admins: 
          - ansible
    - config_nfs_client
    - role: nas_h5ai
      becom: yes
    - nas_k3s
    - kube_okd-console
    - kube_ingress_nginx
    - nas_ingress

